--- #YAML:1.0
name: Config-Irssi-Parser
version: 0.0.2
author: Dylan William Hardison <dhardison@cpan.org>
abstract: Read Irssi-style config files
license: perl
requires:
  perl: 5.8.0
provides:
  Config::Irssi::Parser:
    file: lib/Config/Irssi/Parser.pm
generated_by: Module::Build version 0.25
